---
- name: ensure timezone is set in apache2 php.ini
  become: yes
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache
  become: yes
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'
