---
- name: Install PHPBrew dependencies
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - re2c
    - libxml2
    - libfreetype6
    - libpng12-0
    - libjpeg8
    - libgd3
    - libxpm4
    - libxslt1.1
    - libltdl7
    - openssl
    - gettext
    - libgettextpo0
    - libmhash2
    - libmcrypt4
    - libbz2-1.0
    - libreadline6
    - libicu52
    - php5-gd
    - p7zip-full
  when: php.version

- name: Install PHPBrew pre-built packages dependencies
  become: yes
  apt: pkg=git state=latest

- name: Check if PHPBrew is installed
  stat: path=/usr/local/bin/phpbrew
  register: phpbrew_service_check

- name: Install PHPBrew
  become: yes
  shell: "{{ item }}"
  with_items:
    - wget -P /home/vagrant/ https://github.com/phpbrew/phpbrew/raw/master/phpbrew
    - chmod +x /home/vagrant/phpbrew
    - mv /home/vagrant/phpbrew /usr/local/bin/phpbrew
  when: php.version and not phpbrew_service_check.stat.exists

- name: Initiate PHPBrew
  shell: phpbrew init && echo "[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc" >> /home/vagrant/.bashrc
  when: php.version and not phpbrew_service_check.stat.exists

- name: Clone out PHPBrew builds
  git:
    repo: "{{ php.phpbrew.cache.repo }}"
    depth: "{{ php.phpbrew.cache.depth }}"
    version: "{{ php.phpbrew.cache.ref }}"
    force: true
    dest: /home/vagrant/.phpbrew/php_build_archives
    update: "{{ php.phpbrew.cache['update'] }}"
  register: phpbrew_clone_builds
  when: php.version and php.phpbrew.cache.repo

- name: Create extracted directory
  file: path=/home/vagrant/.phpbrew/php_build_extracted state=directory
  when: php.version and php.phpbrew.cache.repo

- name: Extract PHPBrew builds
  shell: ls /home/vagrant/.phpbrew/php_build_archives/*.7z | xargs -i sh -c '7z x -so {} | tar xf - -C /home/vagrant/.phpbrew/php_build_extracted/'
  when: php.version and php.phpbrew.cache.repo and phpbrew_clone_builds.changed

- name: Sync extracted builds
  shell: rsync -r -a /home/vagrant/.phpbrew/php_build_extracted/ /home/vagrant/.phpbrew/php warn=no
  when: php.version and php.phpbrew.cache.repo

- name: Add PHP switching scripts
  become: yes
  template: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
    - phpversionformer
    - phpswitch
    - phpbuild
  when: php.version

  # Without alias bash session has to be restarted to change php version.
- name: Create alias for phpswitching script
  shell: echo "alias phpswitch='. phpswitch'" >> /home/vagrant/.bashrc
  when: php.version and not phpbrew_service_check.stat.exists

- name: Check if required php version is already installed
  shell: phpbrew list | grep `phpversionformer {{ php.version }}`
  # grep will exit with 1 when no results found and this fails the task.
  ignore_errors: yes
  register: php_version_check
  when: php.version

- name: Build PHP version
  shell: /usr/local/bin/phpbuild {{ php.version }}
  when: php.version and php_version_check.stdout == ""

- name: Switch to PHP version
  shell: /usr/local/bin/phpswitch {{ php.version }}
  when: php.version

- name: Turn off PHPBrew
  shell: /usr/local/bin/phpswitch off
  when: not php.version and phpbrew_service_check.stat.exists
